stages:
  preprocess:
    cmd: python -m src.run_preprocess
    deps:
      - src/run_preprocess.py
      - src/preprocessor.py
      - src/saving_loading/save_preprocessing.py
      - data/raw/train.csv
    outs:
      - data/processed/X.csv
      - data/processed/y.csv
      - artifacts/preprocessors/preprocessor.joblib

  train:
    cmd: python main.py
    deps:
      - main.py
      - src/train.py
      - src/evaluate.py
      - data/processed/X.csv
      - data/processed/y.csv
    outs:
      - artifacts/models/
      - reports/