import pandas as pd
import hydra
from omegaconf import DictConfig, OmegaConf
from pathlib import Path

import sklearn.ensemble
import sklearn.linear_model
import mlflow

from src.train import train
from src.evaluate import evaluate_model

# Setup paths
ROOT_DIR = Path(__file__).resolve().parent
PROCESSED_DIR = ROOT_DIR / "data" / "processed"
X_PATH = PROCESSED_DIR / "X.csv"
Y_PATH = PROCESSED_DIR / "y.csv"

@hydra.main(version_base="1.3", config_path="config", config_name="model")
def main(cfg: DictConfig):
    print("=== Starting Model Training Stage ===\n")

    # 1. Standard MLflow Setup
    mlflow.set_tracking_uri(cfg.model.tracking_uri)
    experiment_name = "Titanic_Standard_Training"
    mlflow.set_experiment(experiment_name)
    print(f"[MLFLOW] Logging to Experiment: {experiment_name}")

    # 2. Load the Configuration
    model_name = cfg.model.name
    model_params = OmegaConf.to_container(cfg.model.params, resolve=True)

    # 3. Load the PROCESSED data (Generated by your first DVC stage)
    print("Loading processed data...")
    X = pd.read_csv(X_PATH)
    y = pd.read_csv(Y_PATH).values.ravel()

    # 4. Instantiate the Model
    if hasattr(sklearn.ensemble, model_name):
        model_class = getattr(sklearn.ensemble, model_name)
    elif hasattr(sklearn.linear_model, model_name):
        model_class = getattr(sklearn.linear_model, model_name)
    else:
        raise ValueError(f"Model '{model_name}' not found.")
    
    model = model_class(**model_params)

    # --- START MLFLOW RUN ---
    with mlflow.start_run(run_name=model_name):
        print("Training model...")
        mlflow.log_param("model_type", model_name)
        mlflow.log_params(model_params)

        param_string = "_".join([f"{k}-{v}" for k, v in model_params.items()])
        artifact_base_name = f"{model_name}_{param_string}"
        
        # Train the model
        train(model, X, y, artifact_base_name)

        # Evaluate the model
        evaluate_model(model, X, y, artifact_base_name)

if __name__ == "__main__":
    main()